# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0002_auto_20151207_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelog',
            name='object_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
